pipeline {
    agent any
    stages { 
        stage('Setup') {
            steps {
                script {
                    startZap(host: "localhost", port: 9091, timeout:1200, zapHome: "/var/jenkins_home/jobs/ZAP_Pipline/ZAP_2.8.1", allowedHosts:['github.com']) // Start ZAP at /opt/zaproxy/zap.sh, allowing scans on github.com
                }
            }
        }
    }
    post {
        always {
            script {
                archiveZap(failAllAlerts: 1, failHighAlerts: 0, failMediumAlerts: 0, failLowAlerts: 0, falsePositivesFilePath: "zapFalsePositives.json")
            }
        }
    }
}
